version: "3.1"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: JaeTfPFN7c893xvesmOe95ipWYsLJ09z
      POSTGRES_DB: baba
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data