"""empty message

Revision ID: ac4f259a6321
Revises: 217698c36fba
Create Date: 2024-02-07 21:56:09.794881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac4f259a6321'
down_revision: Union[str, None] = '217698c36fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event', sa.Column('voting_until', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event', sa.Column('checkin_from', sa.DateTime(timezone=True), nullable=False))
    op.add_column('event', sa.Column('checkin_until', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('event', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('event', 'checkin_until')
    op.drop_column('event', 'checkin_from')
    op.drop_column('event', 'voting_until')
    op.drop_column('event', 'end_date')
    op.drop_column('event', 'start_date')
    # ### end Alembic commands ###
