"""empty message

Revision ID: af3faea667d3
Revises: 1471e1ca0549
Create Date: 2024-05-06 16:14:58.356533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af3faea667d3'
down_revision: Union[str, None] = '1471e1ca0549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'teamplayer',
        sa.Column(
            'order',
            sa.Integer(),
            nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teamplayer', 'order')
    # ### end Alembic commands ###
